#!/usr/bin/env python3
"""
RING-NATIVE PLIC  —  3-D Volume-of-Fluid interface reconstruction on Z_256.

Every object here is from the MPRC framework; nothing is imported from a
floating-point PLIC formulation.

  state alphabet     Z_256                       (volume fraction, normal, offset)
  L1 normalisation   n_x + n_y + n_z = 256       (ring closure; makes V cubic)
  the four anchors   {0, 64, 128, 192}           axis-aligned orientations,
                                                 where 6 n_x n_y n_z = 0
  the +2 bridge      step across a degenerate orientation
                     ( = Delta^2(k^2), the curvature quantum )
  the k^d law        Delta^d (k^d) = d!          d=3 -> 6 -> V is generated by
                                                 three integer accumulators
  ADI accumulation   Lambda = n_x+n_y+n_z+alpha = 256 + alpha
                     encoded unimodularly (det = 1) so it is closed on Z_256

No floating point appears in the reconstruction path.
"""
import numpy as np
from fractions import Fraction as F

S = 256                     # ring modulus
ANCHORS = (0, 64, 128, 192)
BRIDGE  = 2                 # = Delta^2(k^2) = 2! ; also p_+ - p_-

# ────────────────────────────────────────────────────────────────────
# 1.  ADI cell encoding — unimodular, closed on Z_256, no division
# ────────────────────────────────────────────────────────────────────
def adi_encode(nx, ny, nz, alpha):
    """(n,alpha) -> (Lambda, n_y, n_z, alpha).  det = 1."""
    return ((nx + ny + nz + alpha) % S, ny % S, nz % S, alpha % S)

def adi_decode(L, ny, nz, alpha):
    """exact inverse: one subtraction, no inverse element needed."""
    return ((L - ny - nz - alpha) % S, ny, nz, alpha)

# ────────────────────────────────────────────────────────────────────
# 2.  Anchors and the +2 bridge
# ────────────────────────────────────────────────────────────────────
def is_anchor(n):
    """degenerate orientation: some component is zero -> 6 nx ny nz = 0."""
    return any(c == 0 for c in n)

def bridge(n):
    """step a degenerate normal off the anchor by the +2 quantum, L1-preserving."""
    n = list(n)
    z = [i for i, c in enumerate(n) if c == 0]
    if not z: return tuple(n)
    big = max(range(3), key=lambda i: n[i])
    for i in z:
        n[i] += BRIDGE
        n[big] -= BRIDGE
    return tuple(n)

# ────────────────────────────────────────────────────────────────────
# 3.  The volume function by the k^3 difference table  (three int adds)
# ────────────────────────────────────────────────────────────────────
def vol_exact(n, a):
    """exact rational volume fraction; n integers summing to S, a integer."""
    m = sorted(n); nx, ny, nz = (F(c, S) for c in m); A = F(a, S)
    if A <= 0: return F(0)
    if A >= 1: return F(1)
    Fc = lambda t: F(0) if t <= 0 else t**3
    den = 6*nx*ny*nz
    if den == 0:                                   # anchor / degenerate branch
        pos = [c for c in (nx, ny, nz) if c > 0]
        if len(pos) == 1: return min(F(1), A/pos[0])
        p, q = pos[0], pos[1]
        if A <= min(p, q): return A*A/(2*p*q)
        if A >= p+q:       return F(1)
        if A <= max(p, q): return (A - min(p, q)/2)/max(p, q)
        b = p+q-A;         return 1 - b*b/(2*p*q)
    return (Fc(A) - Fc(A-nx) - Fc(A-ny) - Fc(A-nz)
            + Fc(A-nx-ny) + Fc(A-nx-nz) + Fc(A-ny-nz) - Fc(A-1)) / den

def branch_table(n, a0):
    """Newton forward differences at a0 -> (V, D1, D2, D3). D3 is constant."""
    V = [vol_exact(n, a0+j) for j in range(4)]
    D1 = V[1]-V[0]; D2 = V[2]-2*V[1]+V[0]; D3 = V[3]-3*V[2]+3*V[1]-V[0]
    return V[0], D1, D2, D3

def march(n, a0, steps):
    """generate the branch with three accumulator updates per step."""
    V, D1, D2, D3 = branch_table(n, a0)
    out = [V]
    for _ in range(steps):
        V = V + D1; D1 = D1 + D2; D2 = D2 + D3
        out.append(V)
    return out

# ────────────────────────────────────────────────────────────────────
# 4.  Offset inversion — 8 integer compares, no cube root
# ────────────────────────────────────────────────────────────────────
def invert_offset(n, f_int):
    """given L1-normalised integer normal and 8-bit target fraction, return alpha."""
    target = F(f_int, S)
    lo, hi = 0, S
    while hi - lo > 1:                              # exactly 8 iterations
        mid = (lo + hi) >> 1
        if vol_exact(n, mid) < target: lo = mid
        else: hi = mid
    return lo

# ────────────────────────────────────────────────────────────────────
# 5.  Curvature by the k^2 law — integer second differences
# ────────────────────────────────────────────────────────────────────
def curvature_int(h_int, scale=S):
    """h_int: integer heights on a unit-spaced stencil. Returns kappa."""
    hpp = (h_int[1] - 2*h_int[2] + h_int[3]) / scale
    hp  = (h_int[3] - h_int[1]) / (2*scale)
    return hpp / (1 + hp*hp)**1.5                   # the only root; a 256-entry LUT

if __name__ == "__main__":
    rng = np.random.default_rng(0)
    print("="*74); print("RING-NATIVE PLIC — validation"); print("="*74)

    # 1. encoding
    bad = 0
    for _ in range(200000):
        v = tuple(int(x) for x in rng.integers(0, S, 4))
        if adi_decode(*adi_encode(*v)) != v: bad += 1
    print(f"\n1. ADI unimodular encode/decode, full mod-{S}: 200,000 trials, {bad} failures")

    # 2. Lambda = 256 + alpha under L1 normalisation
    bad = 0
    for _ in range(100000):
        nx = int(rng.integers(1, S-1)); ny = int(rng.integers(1, S-nx))
        nz = S-nx-ny
        if nz < 1: continue
        al = int(rng.integers(0, S+1))
        if nx+ny+nz+al != S+al: bad += 1
    print(f"2. Lambda = 256 + alpha (L1-normalised):     100,000 trials, {bad} failures")

    # 3. k^3 difference table reproduces the branch exactly
    n = (128, 77, 51)
    a0 = 10
    gen = march(n, a0, 8)
    ref = [vol_exact(n, a0+j) for j in range(9)]
    print(f"3. k^3 table (3 int adds/step) vs closed form: "
          f"{'EXACT for 9 steps' if gen == ref else 'MISMATCH'}")
    _,_,_,D3 = branch_table(n, a0)
    print(f"   Delta^3 = {D3}  (constant; Delta^4 = 0)")

    # 4. anchors and the bridge
    print(f"4. anchor detection and +2 bridge:")
    for n0 in [(256,0,0),(128,128,0),(200,56,0),(100,100,56)]:
        b = bridge(n0)
        print(f"     n={str(n0):<16} anchor={str(is_anchor(n0)):<5} "
              f"bridged={str(b):<16} L1={sum(b)}  degenerate now={is_anchor(b)}")

    # 5. offset inversion accuracy
    errs = []
    for _ in range(2000):
        nx = int(rng.integers(20, S-40)); ny = int(rng.integers(20, S-nx-20))
        nz = S-nx-ny
        if nz < 20: continue
        f_int = int(rng.integers(1, S))
        a = invert_offset((nx,ny,nz), f_int)
        errs.append(abs(float(vol_exact((nx,ny,nz), a) - F(f_int,S))))
    errs = np.array(errs)
    print(f"5. offset inversion, 8 integer compares, no cube root:")
    print(f"     {len(errs)} cases  mean err {errs.mean():.3e}  max {errs.max():.3e}")

    # 6. curvature on circles
    print(f"6. curvature from integer 2nd differences (k^2 law), no trig:")
    print(f"     {'R':>6} {'kappa_true':>11} {'kappa_int':>11} {'rel err':>9}")
    for R in (8, 16, 32, 64, 128):
        xs = np.arange(-2, 3)
        h  = R - np.sqrt(R*R - xs*xs)
        hq = np.rint(h*S).astype(np.int64)
        k  = curvature_int(hq)
        print(f"     {R:>6} {1/R:>11.6f} {k:>11.6f} {abs(k-1/R)/(1/R):>9.2%}")
